## This file provides default values to modules using the secrets-gradle-plugin. It is necessary
# because the secrets properties file is not under source control so CI builds will fail without
# default values.
API_URL="https://api.sporthor.com/api/"
MEDIA_FILE_PREFIX_URL="https://api.sporthor.com"
SOCKET_URL="https://socket.sporthor.com/chathub"
GOOGLE_MAPS_KEY="AIzaSyDVFakk3xpgr72bxCha-MLwA5UJ-C4goVs"
