## This file provides default values to modules using the secrets-gradle-plugin. It is necessary
# because the secrets properties file is not under source control so CI builds will fail without
# default values.
WEBSITE_ADDRESS="-"
TERMS_ADDRESS="-"
PRIVACY_POLICY_ADDRESS="-"
CONTACT_ADDRESS="-"
GOOGLE_PLAY_ADDRESS="-"
GOOGLE_PLAY_DEV_ACCOUNT_PROFILE_ADDRESS="-"
GOOGLE_SERVICE_CLIENT_ID="275755443371-6njsvt2mi8js03rve7p74o40p1r8444b.apps.googleusercontent.com"
