[versions]
namespace = "com.sporthor.as"
applicationId = "com.sporthor.as"
targetSdk = "36"
compileSdk = "36"
minSdk = "24"
versionName = "1.0.0.542"
versionCode = "20261204"
testRunner = "androidx.test.runner.AndroidJUnitRunner"
minifyEnabledDebug = "false"
minifyEnabledRelease = "true"

androidGradlePlugin = "8.11.1"
kotlin = "2.2.0"
ksp = "2.2.0-2.0.2"
androidxActivity = "1.10.1"
androidxAppCompat = "1.7.1"
androidxBrowser = "1.9.0"
androidxComposeBom = "2025.07.00"
playServicesLocation = "21.3.0"
google-maps-compose = "6.7.0"
googleServices = "4.4.3"
lottieVersion = "6.6.7"
constraintlayout-compose = "1.1.1"
androidxComposeRuntimeTracing = "1.8.3"
androidxCore = "1.16.0"
androidxCoreSplashscreen = "1.0.1"
androidxDataStore = "1.1.7"
androidxHiltNavigationCompose = "1.2.0"
androidxLifecycle = "2.9.2"
androidxMetrics = "1.0.0-beta02"
androidxNavigation = "2.9.3"
androidxWearCompose = "1.0.0-alpha37"
androidxProfileinstaller = "1.4.1"
androidxTestCore = "1.7.0"
androidxEspresso = "3.7.0"
androidxTestExt = "1.3.0"
androidxTestRules = "1.7.0"
androidxTestRunner = "1.7.0"
androidxUiAutomator = "2.3.0"
androidxTracing = "1.3.0"
androidxWindowManager = "1.4.0"
androidxWork = "2.10.3"
androidxCamera = "1.4.2"
androidxConcurrentFutures = "1.3.0"
mockk = "1.14.5"
turbine = "1.2.1"
kotest = "5.9.1"
konsist = "0.17.3"
coil = "3.3.0"
hilt = "2.57"
hiltExt = "1.2.0"
junit4 = "4.13.2"
kotlinx-collections-immutable = "0.4.0"
kotlinxCoroutines = "1.10.2"
kotlinxDatetime = "0.7.1"
kotlinxSerializationJson = "1.9.0"
ktlint = "13.0.0"
nlopezComposeRules = "0.4.26"
roborazzi = "1.46.1"
room = "2.7.2"
java-websocket = "1.6.0"
signalr = "10.0.0-preview.6.25358.103"
slf4j = "2.0.17"
timberVersion = "5.0.1"
detekt = "1.23.8"
firebase-bom = "34.0.0"
firebaseCrashlyicsGradle = "3.0.5"
googlePlayServicesAds = "24.5.0"
googlePlayReview = "2.0.2"
googleCredentials = "1.5.0"
googleLibraryIdentityGoogleId = "1.1.1"
googleGuava = "33.4.8-jre"
google-android-libraries-places = "4.4.1"
javaxInject = "1"
retrofit = "3.0.0"
okhttp3 = "5.1.0"
network-retrofit-kotlinx-serialization-converter = "3.0.0"
chucker = "4.2.0"
paging-compose = "3.3.6"
junit = "1.3.0"
material = "1.12.0"
jwtdecode = "2.0.2"
pdf-viewer = "2.3.7"
photoeditor = "3.0.2"
secrets = "2.0.1"
spotless = "7.2.1"
androidR8Libs = "8.11.18"
androidDesugarJdkLibs = "2.1.5"
robolectric = "4.15.1"
exoPlayer = "1.8.0"
accompanist = "0.37.3"
devIurysouzaModulegraph = "0.12.0"
jraskaModuleGraphAssertion = "2.9.0"

[libraries]
#
# AndroidX dependencies
#
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidxBrowser" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-core-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "androidxCoreSplashscreen" }
androidx-dataStore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDataStore" }
androidx-metrics = { group = "androidx.metrics", name = "metrics-performance", version.ref = "androidxMetrics" }
androidx-profileinstaller = { group = "androidx.profileinstaller", name = "profileinstaller", version.ref = "androidxProfileinstaller" }
androidx-tracing-ktx = { group = "androidx.tracing", name = "tracing-ktx", version.ref = "androidxTracing" }
androidx-window-manager = { module = "androidx.window:window", version.ref = "androidxWindowManager" }
androidx-work-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "androidxWork" }
androidx-camera-core = { group = "androidx.camera", name = "camera-core", version.ref = "androidxCamera" }
androidx-camera-camera2 = { group = "androidx.camera", name = "camera-camera2", version.ref = "androidxCamera" }
androidx-camera-lifecycle = { group = "androidx.camera", name = "camera-lifecycle", version.ref = "androidxCamera" }
androidx-camera-video = { group = "androidx.camera", name = "camera-video", version.ref = "androidxCamera" }
androidx-camera-view = { group = "androidx.camera", name = "camera-view", version.ref = "androidxCamera" }
androidx-camera-extensions = { group = "androidx.camera", name = "camera-extensions", version.ref = "androidxCamera"}
androidx-concurrent-futures = { group = "androidx.concurrent", name = "concurrent-futures", version.ref = "androidxConcurrentFutures" }
androidx-concurrent-futures-ktx = { group = "androidx.concurrent", name = "concurrent-futures-ktx", version.ref = "androidxConcurrentFutures" }

#
# Compose Dependencies
#
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-compose-foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material3-windowSizeClass = { group = "androidx.compose.material3", name = "material3-window-size-class" }
androidx-compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
androidx-compose-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-ui-test = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-compose-ui-testManifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-util = { group = "androidx.compose.ui", name = "ui-util" }
androidx-compose-runtime-tracing = { group = "androidx.compose.runtime", name = "runtime-tracing", version.ref = "androidxComposeRuntimeTracing" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-navigation-dynamic-features = { group = "androidx.navigation", name = "navigation-dynamic-features-fragment", version.ref = "androidxNavigation" }
androidx-navigation-safeArgs = { group = "androidx.navigation", name = "navigation-safe-args-gradle-plugin", version.ref = "androidxNavigation" }
androidx-navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "androidxNavigation" }
androidx-wear-compose = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "androidxWearCompose" }

#
# Animation Dependencies
#
airbnb-lottie-compose = { group = "com.airbnb.android", name = "lottie-compose", version.ref = "lottieVersion" }

#
# Hilt Dependencies
#
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-android-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
hilt-ext-compiler = { group = "androidx.hilt", name = "hilt-compiler", version.ref = "hiltExt" }
hilt-ext-work = { group = "androidx.hilt", name = "hilt-work", version.ref = "hiltExt" }

#
# Lifecycle Dependencies
#
androidx-lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }

#
# Test Dependencies
#
androidx-test-core = { group = "androidx.test", name = "core", version.ref = "androidxTestCore" }
androidx-test-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspresso" }
androidx-test-ext = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "androidxTestExt" }
androidx-test-rules = { group = "androidx.test", name = "rules", version.ref = "androidxTestRules" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidxTestRunner" }
androidx-test-uiautomator = { group = "androidx.test.uiautomator", name = "uiautomator", version.ref = "androidxUiAutomator" }
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
work-testing = { group = "androidx.work", name = "work-testing", version.ref = "androidxWork" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
turbine = { group = "app.cash.turbine", name = "turbine", version.ref = "turbine"}
kotest = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest"}
konsist = { group = "com.lemonappdev", name = "konsist", version.ref = "konsist" }

#
# Coil Dependencies
#
coil-kt = { group = "io.coil-kt.coil3", name = "coil", version.ref = "coil" }
coil-kt-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil" }
coil-kt-svg = { group = "io.coil-kt.coil3", name = "coil-svg", version.ref = "coil" }
coil-kt-video = { group = "io.coil-kt.coil3", name = "coil-video", version.ref = "coil" }
coil-kt-gif = { group = "io.coil-kt.coil3", name = "coil-gif", version.ref = "coil" }
coil-kt-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil" }

#
# Firebase Dependencies
#
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-installations = { module = "com.google.firebase:firebase-installations" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
firebase-inappmessaging = { module = "com.google.firebase:firebase-inappmessaging-display" }
firebase-perf = { module = "com.google.firebase:firebase-perf" }
firebase-remoteconfig = { module = "com.google.firebase:firebase-config" }

#
# Google Dependencies
#
google-play-services-location = { module = "com.google.android.gms:play-services-location", version.ref = "playServicesLocation" }
google-maps-compose = { group = "com.google.maps.android", name = "maps-compose", version.ref = "google-maps-compose" }
google-play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "googlePlayServicesAds"}
google-accompanist-permission = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanist" }
google-play-review = { group = "com.google.android.play", name = "review-ktx", version.ref = "googlePlayReview" }
google-credentials = { group = "androidx.credentials", name = "credentials", version.ref = "googleCredentials" }
google-credentials-play-services-auth = { group = "androidx.credentials", name = "credentials-play-services-auth", version.ref = "googleCredentials" }
google-libraries-identity-google-id = { group = "com.google.android.libraries.identity.googleid", name = "googleid", version.ref = "googleLibraryIdentityGoogleId" }
google-guava = { group = "com.google.guava", name = "guava", version.ref = "googleGuava" }
google-android-libraries-places = { group = "com.google.android.libraries.places", name = "places", version.ref = "google-android-libraries-places" }

#
# Kotlin & Coroutine Dependencies
#
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-guava = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-guava", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }

#
# Lint Dependencies
#
ktlint-ruleset-compose = { group = "io.nlopez.compose.rules", name = "ktlint", version.ref = "nlopezComposeRules" }
detekt-ruleset-compose = { group = "io.nlopez.compose.rules", name = "detekt", version.ref = "nlopezComposeRules" }
#
# Room Dependencies
#
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }

#
# Network Dependencies
#
network-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
network-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
network-retrofit-kotlinx-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref = "network-retrofit-kotlinx-serialization-converter" }
network-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp3" }

#
# Exo Player
#
exo-player = { group = "androidx.media3", name = "media3-exoplayer", version.ref = "exoPlayer" }
exo-player-ui = { group = "androidx.media3", name = "media3-ui", version.ref = "exoPlayer" }
exo-player-ui-compose = { group = "androidx.media3", name = "media3-ui-compose", version.ref = "exoPlayer" }

#
# Chucker
#
chucker-library = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op", version.ref = "chucker" }

#
# Paging
#
paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging-compose" }
paging-compose = { group = "androidx.paging", name = "paging-compose", version.ref = "paging-compose" }

#
# Other
#
java-websocket = { group = "org.java-websocket", name = "Java-WebSocket", version.ref = "java-websocket" }
signalr = { group = "com.microsoft.signalr", name = "signalr", version.ref = "signalr" }
slf4j = { group = "org.slf4j", name = "slf4j-jdk14", version.ref = "slf4j" }
slf4j-nop = { group = "org.slf4j", name = "slf4j-nop", version.ref = "slf4j" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timberVersion" }
javax-inject = { group = "javax.inject", name = "javax.inject", version.ref = "javaxInject"}
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
jwtdecode = { group = "com.auth0.android", name = "jwtdecode", version.ref = "jwtdecode" }
pdf-viewer = { group = "io.github.afreakyelf", name = "Pdf-Viewer", version.ref = "pdf-viewer" }
photoeditor = { group = "com.burhanrashid52", name = "photoeditor", version.ref = "photoeditor" }

#
# Test
#
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
robolectric-shadows = { group = "org.robolectric", name = "shadows-framework", version.ref = "robolectric" }
roborazzi = { group = "io.github.takahirom.roborazzi", name = "roborazzi", version.ref = "roborazzi" }

#
# Gradle
#
android-tools-r8 = { group = "com.android.tools", name = "r8", version.ref = "androidR8Libs" }
android-desugarJdkLibs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "androidDesugarJdkLibs" }
android-gradle-plugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradle-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
ksp-gradle-plugin = { group = "com.google.devtools.ksp", name = "com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }
ktlint-gradle-plugin = { group = "org.jlleitschuh.gradle", name = "ktlint-gradle", version.ref = "ktlint" }
detekt-gradle-plugin = { group = "io.gitlab.arturbosch.detekt", name = "detekt-gradle-plugin", version.ref = "detekt" }
spotless-gradle-plugin = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version.ref = "spotless" }
secrets-gradle-plugin = { module = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin:secrets-gradle-plugin", version.ref = "secrets" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize",  version.ref = "kotlin"  }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
roborazzi = { id = "io.github.takahirom.roborazzi", version.ref = "roborazzi" }
secrets = { id = "com.google.android.libraries.mapsplatform.secrets-gradle-plugin", version.ref = "secrets" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyicsGradle"}
dev-iurysouza-modulegraph = { id = "dev.iurysouza.modulegraph", version.ref = "devIurysouzaModulegraph" }
jraska-module-graph-assertion = { id = "com.jraska.module.graph.assertion", version.ref = "jraskaModuleGraphAssertion" }

# Plugins defined by this project
build-logic-group = { id = "com.iamkurtgoz.app.buildlogic" }
build-logic-android-application = { id = "com.iamkurtgoz.android.application" }
build-logic-android-application-compose = { id = "com.iamkurtgoz.android.application.compose" }
build-logic-android-library = { id = "com.iamkurtgoz.android.library" }
build-logic-android-library-compose = { id = "com.iamkurtgoz.android.library.compose" }
build-logic-android-library-design-system-compose = { id = "com.iamkurtgoz.android.library.design.system.compose" }
build-logic-android-feature = { id = "com.iamkurtgoz.android.feature" }
build-logic-sub-timber = { id = "com.iamkurtgoz.sub.timber" }
build-logic-sub-hilt = { id = "com.iamkurtgoz.sub.hilt" }
build-logic-sub-ktlint = { id = "com.iamkurtgoz.sub.ktlint" }
build-logic-sub-spotless = { id = "com.iamkurtgoz.sub.spotless" }
build-logic-sub-firebase = { id = "com.iamkurtgoz.sub.firebase" }
build-logic-sub-detekt = { id = "com.iamkurtgoz.sub.detekt" }
build-logic-sub-coil = { id = "com.iamkurtgoz.sub.coil" }
build-logic-sub-test = { id = "com.iamkurtgoz.sub.test" }
build-logic-sub-flavor = { id = "com.iamkurtgoz.sub.flavor" }
